### cpu信息
GET http://localhost:8083/cpu
Accept: application/json

### 内存信息
GET http://localhost:8083/memory
Accept: application/json

### 系统启动时长
GET http://localhost:8083/bootTime
Accept: application/json

### 网络1秒内的下载速度
GET http://localhost:8083/netIo
Accept: application/json

### ip
GET http://localhost:8083/ip
Accept: application/json

###